install: true

script: true

after_success:
- pip install awscli --upgrade --user
- zip -r myLambda.zip myLambda
- aws --region us-east-1 lambda update-function-code --function-name myLambdaFunction --zip-file fileb://myLambda.zip
